apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scraper-http-worker-scaler
  namespace: k-scrape-nexus
  labels:
    app.kubernetes.io/name: k-scrape-nexus
    app.kubernetes.io/component: scraper-http-worker
spec:
  scaleTargetRef:
    name: scraper-http-worker
  minReplicaCount: 2
  maxReplicaCount: 50
  pollingInterval: 15
  cooldownPeriod: 180
  triggers:
  - type: redis-streams
    metadata:
      address: redis:6379
      stream: scrape_http
      consumerGroup: http_workers
      pendingEntriesCount: "10"
      activationPendingEntriesCount: "2"
      lagThreshold: "50"