apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: crawl4ai-scraper-worker-scaler
  namespace: k-scrape-nexus
  labels:
    app.kubernetes.io/name: k-scrape-nexus
    app.kubernetes.io/component: crawl4ai-scraper-worker
spec:
  scaleTargetRef:
    name: crawl4ai-scraper-worker
  pollingInterval: 30
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: redis
    metadata:
      address: redis:6379
      listName: scrape_crawl4ai
      listLength: "5"
      enableTLS: "false"
    authenticationRef:
      name: redis-auth
  - type: prometheus
    metadata:
      serverAddress: http://prometheus:9090
      metricName: crawl4ai_queue_processing_rate
      threshold: '0.8'
      query: rate(crawl4ai_requests_total[5m])
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 10
            periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 60
          policies:
          - type: Percent
            value: 50
            periodSeconds: 60
          - type: Pods
            value: 2
            periodSeconds: 60
          selectPolicy: Max