global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # K-Scrape Nexus services (when running locally)
  - job_name: 'k-scrape-api-server'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'k-scrape-ingestion-service'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'k-scrape-workers'
    static_configs:
      - targets: 
        - 'host.docker.internal:8003'  # HTTP Worker
        - 'host.docker.internal:8004'  # Headless Worker
        - 'host.docker.internal:8005'  # Processing Worker
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'k-scrape-coordinator'
    static_configs:
      - targets: ['host.docker.internal:8006']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Infrastructure monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
# rule_files:
#   - alert_rules.yml