apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
  namespace: k-scrape-nexus
  labels:
    app.kubernetes.io/name: k-scrape-nexus
    app.kubernetes.io/component: nginx-load-balancer
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    app.kubernetes.io/name: k-scrape-nexus
    app.kubernetes.io/component: nginx-load-balancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer-internal
  namespace: k-scrape-nexus
  labels:
    app.kubernetes.io/name: k-scrape-nexus
    app.kubernetes.io/component: nginx-load-balancer
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: health
    port: 8080
    targetPort: health
    protocol: TCP
  selector:
    app.kubernetes.io/name: k-scrape-nexus
    app.kubernetes.io/component: nginx-load-balancer