apiVersion: v1
kind: Service
metadata:
  name: coordinator
  namespace: k-scrape-nexus
  labels:
    app.kubernetes.io/name: k-scrape-nexus
    app.kubernetes.io/component: coordinator
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8006
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: k-scrape-nexus
    app.kubernetes.io/component: coordinator