apiVersion: v1
kind: ConfigMap
metadata:
  name: k-scrape-nexus-config
  namespace: k-scrape-nexus-staging
data:
  # Staging-specific overrides
  DEBUG: "true"
  LOG_LEVEL: "DEBUG"
  
  # Reduced resource settings for staging
  WORKER_CONCURRENCY: "5"
  WORKER_TIMEOUT: "180"
  
  # Staging database and Redis
  DATABASE_POOL_SIZE: "5"
  REDIS_MAX_CONNECTIONS: "25"
  
  # Staging scraping limits
  SCRAPING_TIMEOUT: "20"
  RATE_LIMIT_RPS: "5.0"
  RATE_LIMIT_BURST: "10"
  
  # File processing limits
  MAX_FILE_SIZE_MB: "50"