apiVersion: v1
kind: Secret
metadata:
  name: k-scrape-nexus-secrets
  namespace: k-scrape-nexus
  labels:
    app.kubernetes.io/name: k-scrape-nexus
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vdXNlcjpwYXNzd29yZEBwb3N0Z3Jlc3FsOjU0MzIvay1zY3JhcGUtbmV4dXM=
  
  # Redis credentials
  REDIS_URL: cmVkaXM6Ly9yZWRpczozNzM2LzA=
  
  # S3 credentials
  S3_BUCKET: ay1zY3JhcGUtbmV4dXMtZGF0YQ==
  S3_ENDPOINT_URL: aHR0cDovL21pbmlvOjkwMDA=
  AWS_ACCESS_KEY_ID: bWluaW9hZG1pbg==
  AWS_SECRET_ACCESS_KEY: bWluaW9wYXNzd29yZA==
  
  # Application secret key
  SECRET_KEY: c3VwZXItc2VjcmV0LWtleS1mb3ItcHJvZHVjdGlvbi11c2U=
  
  # JWT configuration
  JWT_ALGORITHM: SFMyNTY=
  JWT_EXPIRE_MINUTES: MzA=
  
  # Tracing endpoint
  TRACING_ENDPOINT: aHR0cDovL2phZWdlci1jb2xsZWN0b3I6MTQyNjg=